[package]
name = "surreal_surrealkv"
publish = false
edition = "2024"
rust-version = "1.91.0"
license-file = "../../LICENSE"
resolver = "2"

[dependencies]
shared = { path = "../shared", features = ["surrealkv"] }

[lib]
crate-type = ["cdylib"]
